image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      mkdir -p ../.R/library
      sudo Rscript requirements.r
      pip3 install -r requirements.txt
    command: |
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      source $HOME/.bashrc
      sudo bash -c "echo R_LIBS_USER=$GITPOD_REPO_ROOT/../.R/library > /home/gitpod/.Renviron"
      sudo bash -c "echo 'setwd(\"$GITPOD_REPO_ROOT\")' > /home/gitpod/.Rprofile"
      sudo usermod -a -G rstudio-users gitpod
      sudo usermod --password $(openssl passwd -1 password) gitpod
      sudo rstudio-server restart
ports:
  - port: 8787
    onOpen: open-browser

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - Ikuyadeu.r
    - efoerster.texlab
