---
image:
  file: .gitpod.Dockerfile

ports:
- port: 8787

tasks:
- name: R and Python setup
  init: |
    mkdir -p ../.R/library
    make requirements
  command: |
    sudo bash -c "echo R_LIBS_USER=$GITPOD_REPO_ROOT/../.R/library > /home/gitpod/.Renviron"
    ln -s /workspace/captain-scarlet /home/gitpod/captain-scarlet
    # https://stackoverflow.com/questions/47541007/how-to-i-bypass-the-login-page-on-rstudio
    sudo usermod -a -G sudo gitpod
    sudo bash -c "echo 'server-user=gitpod' >> /etc/rstudio/rserver.conf"
    sudo bash -c "echo 'auth-none=1' >> /etc/rstudio/rserver.conf"
    # Restart the rserver with sudo otherwise it won't run for the gitpod user (dunno why)
    sudo rserver
    sudo pkill rserver
    alias python='python3'

vscode:
  extensions:
    - bungcip.better-toml
    - eamodio.gitlens
    - ms-python.python
    - ms-python.isort
    - RDebugger.r-debugger
    - reditorsupport.r
    - streetsidesoftware.code-spell-checker
    - sourcery.sourcery
