image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip
    init: |
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      echo 'export PIP_USER=false' >> $HOME/.bashrc
      pip install -r requirements.txt
      gp sync-done pip # 'pip' is an arbitrary tag.
  - name: API Web Server (5000)
    init: gp sync-await pip
    command: |
      export FLASK_APP=flask_app
      export FLASK_ENV=development
      flask run
    openMode: tab-after

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
