---
image:
  file: .devcontainer/Dockerfile

ports:
- port: 8787

tasks:
- init: |
    
- command: |
    sudo bash -c "echo 'setwd(\"$GITPOD_REPO_ROOT\")' > /home/gitpod/.Rprofile"
    # https://stackoverflow.com/questions/47541007/how-to-i-bypass-the-login-page-on-rstudio
    sudo usermod -a -G sudo gitpod
    sudo bash -c "echo 'server-user=gitpod' >> /etc/rstudio/rserver.conf"
    sudo bash -c "echo 'auth-none=1' >> /etc/rstudio/rserver.conf"
    # Start and restart the rserver so the .Rprofile is read
    sudo rserver
    sudo pkill rserver
    rserver

vscode:
  extensions:
    - reditorsupport.r
